apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chartmuseum-frontend-external
  namespace: {{ (datasource "config").chartmuseum.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ (datasource "config").chartmuseum.frontend_subdomain }}.{{ (datasource "config").chartmuseum.domain }}`)
      kind: Rule
      services:
        - name: chartmuseum
          kind: Service
          port: 8080
  tls:
    certResolver: letsencrypt
    domains:
      - main: {{ (datasource "config").chartmuseum.domain }}
        sans: [ "*.{{ (datasource "config").chartmuseum.domain }}"]
